name: ntfy.sh action
description: Send notifications to ntfy.sh using GitHub Action workflow
branding:
  icon: 'upload'
  color: 'blue'
inputs:
  url:
    description: Server URL
    required: true
  topic:
    description: ntfy.sh topic
    required: true
  icon:
    description: icon to be used in the notification
    required: true
  job_status:
    description: status of the job
    required: true
outputs:
  response:
    description: 'The response of POST request'
runs:
  using: 'node16'
  main: 'dist/index.js'